### ISSUE TITLE
Windows Cygwin Build Issues

### ISSUE THREAD

**Issue by richrumble** [archiecobbs/csvprintf#2]
Trying to build this in Cygwin on windows, iconv (devel) is certainly installed:
$ ./autogen.sh
cleaning up
running aclocal
running autoheader
running automake
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake-1.14 line 3930.
configure.ac:41: installing 'scripts/compile'
configure.ac:21: installing 'scripts/install-sh'
configure.ac:21: installing 'scripts/missing'
Makefile.am: installing 'scripts/depcomp'
running autoconf

/cygdrive/d/logs/ad/csvprintf-master
$ ./configure
configure: loading site script /usr/share/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make sets $(MAKE)... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for printf... /usr/bin/printf
checking for xsltproc... /usr/bin/xsltproc
checking for iconv_open in -lc... no
configure: error: required function iconv_open missing

/cygdrive/d/logs/ad/csvprintf-master
$ which iconv
/usr/bin/iconv

I found an old "fork" that used cygport to help with compiling I assume, the patch doesn't seem to work for me when I applied the changes directly to configure.ac.
https://github.com/fd00/yacp/blob/master/csvprintf/csvprintf-1.0.3-1bl1.src.patch

**Comment by archiecobbs** [comment]
Hmm. I tried to fix this with c5db0f8 but that didn't work.

Even with libiconv installed on Cigwin I can't compile the test program:

```
/* confdefs.h */
#define PACKAGE_NAME "csvprintf - Simple CSV file parser for the UNIX command line"
#define PACKAGE_TARNAME "csvprintf"
#define PACKAGE_VERSION "1.0.3"
#define PACKAGE_STRING "csvprintf - Simple CSV file parser for the UNIX command line 1.0.3"
#define PACKAGE_BUGREPORT "https://github.com/archiecobbs/csvprintf"
#define PACKAGE_URL ""
#define PACKAGE "csvprintf"
#define VERSION "1.0.3"
#define _GNU_SOURCE 1
#define _BSD_SOURCE 1
#define _XOPEN_SOURCE 500
#define _DARWIN_C_SOURCE 1
/* end confdefs.h.  */

/* Override any GCC internal prototype to avoid an error.
   Use char because int might match the return type of a GCC
   builtin and then its argument prototype would still apply.  */
#ifdef __cplusplus
extern "C"
#endif
char iconv_open ();
int
main ()
{
return iconv_open ();
  ;
  return 0;
}
```

I get this error:

```
$ gcc -o conftest.exe -DPRINTF_PROGRAM=\"/usr/bin/printf\" xx.c -liconv
/tmp/ccm6TH0C.o:xx.c:(.text+0xe): undefined reference to `iconv_open'
/tmp/ccm6TH0C.o:xx.c:(.text+0xe): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `iconv_open'
collect2: error: ld returned 1 exit status
$ ls -l /usr/lib/libiconv*
-rw-r--r-- 1 Archie Cobbs None 1690230 Feb 20  2015 /usr/lib/libiconv.a
-rwxr-xr-x 1 Archie Cobbs None   10890 Feb 20  2015 /usr/lib/libiconv.dll.a*
```

What am I missing??

**Comment by richrumble** [comment]
I wish I knew, I googled all day. I looked at the patch from that other repo, all he did was drop "c" in configure.ac, bracket it differently, and change/add some libiconv_open. Similar to your attempt.
Again I've not tested his version to see if it worked. He then goes on to use cygport so not sure if that will do anything additional.
I don't know anything about coding, but I've run into enough cygwin errors to get around most things, this one has me stumped. :) Thanks for looking into it!

**Comment by archiecobbs** [comment]
Should be fixed by 8ec5ba8. Can you try it?

This is just a workaround. The underlying problem remains inexplicable.

**Comment by richrumble** [comment]
Yes, this compiles (doesn't find iconv=no)and appears to work! If I can get libxml2 installed on mingw I may try that too, but this appears to be working for now on cygwin. Thanks!

**Comment by archiecobbs** [comment]
Cool, thanks.
