### ISSUE TITLE
Group option

### ISSUE THREAD

**Issue by doekman** [archiecobbs/csvprintf#5]
I think it would be useful if there was a group option. You would specify a special group printf statement, and _csvprintf_  would print  this every time the group changes. 

Example: given the `input.csv`:

    Name,City,Email
    Fred,New York,fred@home.com
    Lilly,New York,itsme@lilly.net
    No Body,Cyberspace,test@example.com

And this will print a grouped  list in MarkDown:

    $ cat input.csv | csvprintf -ig '\n# %2$s\n' '- [%1$s](mailto:%3$s)\n'
    
    # New York
    - [Fred](mailto:fred@home.com)
    - [Lilly](mailto:itsme@lilly.net)
    
    # Cyberspace
    - [No Boddy](mailto:test@example.com)

The CSV is expected to be sorted. Also, with `-G` a group footer can be specified. And optionally, with `-g1` an additional level of grouping can be specified (a number is  necessary, because per level, only a group header or footer needs to be specified). Also, this option would work nice with the XML option.

I thought up this option, because I wanted [some kind of grouped output](https://twitter.com/doekezanstra/status/1063114403535564800) of [a list of awesome CSV tools](https://github.com/secretGeek/awesomecsv) a friend of mine maintains, but `awk` wasn't up to the task...

**Comment by archiecobbs** [comment]
Nice idea, but my first reaction is that this seems outside the scope of `csvprintf`, which is just a simple parsing/formatting tool, not a general purpose data processing tool. Seems like `awk`, `perl`, or even `bash`  would be the right tool for that kind of thing...
```
$ cat input.csv | csvprintf -i -f - '%2$s|%1$s|%3$s\n' \
  | awk -F\| '{ if ($1 != CITY) printf "\n# %s\n", $1; printf "- [%s](mailto:%s)\n", $2, $3; CITY=$1 }'

# New York
- [Fred](mailto:fred@home.com)
- [Lilly](mailto:itsme@lilly.net)

# Cyberspace
- [No Body](mailto:test@example.com)
```
